# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        exclude: \.(min\.css|min\.js|po|mo)$
      - id: end-of-file-fixer
        exclude: \.(min\.css|min\.js|po|mo)$
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: check-added-large-files
        args: [ --maxkb=1000 ]
      - id: check-merge-conflict

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        exclude: ^(LICENSE)
